use crate::hs_database::{CccCertItem, ProhibitedItem};

pub fn get_prohibited_items() -> Vec<ProhibitedItem> {
    vec![
        ProhibitedItem {
            hs_code_prefix: "93".to_string(),
            name: "Arms and Ammunition".to_string(),
            reason: "Weapons, ammunition and their parts are prohibited from cross-border e-commerce import".to_string(),
            regulation: "Customs Law Article 47; Cross-border E-commerce Negative List".to_string(),
            severity: "Critical".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "36".to_string(),
            name: "Explosives and Pyrotechnic Products".to_string(),
            reason: "Explosives, fireworks, flammable goods are prohibited from cross-border e-commerce import".to_string(),
            regulation: "Customs Law Article 47; Fireworks and Firecrackers Safety Management Regulations".to_string(),
            severity: "Critical".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "2844".to_string(),
            name: "Radioactive Materials".to_string(),
            reason: "Radioactive substances and isotopes are strictly prohibited from cross-border e-commerce import".to_string(),
            regulation: "Radioactive Pollution Prevention and Control Law; Customs Prohibited Items List".to_string(),
            severity: "Critical".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "2845".to_string(),
            name: "Radioactive Isotopes".to_string(),
            reason: "Radioactive isotopes and compounds are prohibited from cross-border e-commerce import".to_string(),
            regulation: "Radioactive Pollution Prevention and Control Law".to_string(),
            severity: "Critical".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "29".to_string(),
            name: "Organic Chemicals (Controlled Substances)".to_string(),
            reason: "Certain organic chemicals including precursor chemicals are prohibited; specific sub-categories may be restricted".to_string(),
            regulation: "Narcotic Drugs Control Law; Precursor Chemical Management Regulations".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "2934".to_string(),
            name: "Narcotic Precursor Chemicals".to_string(),
            reason: "Narcotic and psychotropic substance precursors are prohibited from cross-border e-commerce import".to_string(),
            regulation: "Narcotic Drugs Control Law; UN Convention Against Illicit Traffic in Narcotic Drugs".to_string(),
            severity: "Critical".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "30".to_string(),
            name: "Pharmaceutical Products (Restricted)".to_string(),
            reason: "Most pharmaceutical products are restricted from cross-border e-commerce import; only OTC health supplements on positive list may qualify".to_string(),
            regulation: "Drug Administration Law; Cross-border E-commerce Retail Import Positive List".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "3002".to_string(),
            name: "Blood Products and Biological Products".to_string(),
            reason: "Human blood, blood products and biological products are prohibited from cross-border e-commerce import".to_string(),
            regulation: "Blood Donation Law; Drug Administration Law; Entry-Exit Quarantine Law".to_string(),
            severity: "Critical".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "3003".to_string(),
            name: "Medicaments (Not in Packaged Form)".to_string(),
            reason: "Unpackaged medicaments containing antibiotics or hormones are prohibited from cross-border e-commerce import".to_string(),
            regulation: "Drug Administration Law; Cross-border E-commerce Negative List".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "3004".to_string(),
            name: "Medicaments (Packaged)".to_string(),
            reason: "Packaged medicaments are restricted; only OTC drugs on the positive list may be eligible for cross-border e-commerce import".to_string(),
            regulation: "Drug Administration Law; Cross-border E-commerce Retail Import Positive List".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "3006".to_string(),
            name: "Pharmaceutical Goods (Sutures, Blood-grouping Reagents etc.)".to_string(),
            reason: "Special pharmaceutical goods including surgical sutures, blood-grouping reagents are prohibited from cross-border e-commerce import".to_string(),
            regulation: "Drug Administration Law; Medical Device Supervision Regulations".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "27".to_string(),
            name: "Mineral Fuels and Oils".to_string(),
            reason: "Petroleum, natural gas and refined fuel products are prohibited from cross-border e-commerce import".to_string(),
            regulation: "Dangerous Chemicals Safety Management Regulations; Cross-border E-commerce Negative List".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "2710".to_string(),
            name: "Refined Petroleum Products".to_string(),
            reason: "Gasoline, diesel, lubricants and other refined petroleum are prohibited from cross-border e-commerce import".to_string(),
            regulation: "Dangerous Chemicals Safety Management Regulations".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "3824".to_string(),
            name: "Hazardous Chemical Preparations".to_string(),
            reason: "Chemical preparations containing hazardous substances are prohibited from cross-border e-commerce import".to_string(),
            regulation: "Dangerous Chemicals Safety Management Regulations".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "0510".to_string(),
            name: "Animal Products Not Elsewhere Specified".to_string(),
            reason: "Unprocessed animal products including ambergris and animal secretion products may be restricted under wildlife protection laws".to_string(),
            regulation: "Wildlife Protection Law; CITES Convention; Entry-Exit Quarantine Law".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "0511".to_string(),
            name: "Animal Products and Endangered Species Products".to_string(),
            reason: "Products from endangered species (ivory, rhino horn, tiger bone etc.) are strictly prohibited from import".to_string(),
            regulation: "Wildlife Protection Law; CITES Convention; Customs Prohibited Items List".to_string(),
            severity: "Critical".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "1211".to_string(),
            name: "Endangered Plant Species".to_string(),
            reason: "Plants used in pharmacy or for insecticidal purposes may be restricted under CITES and wildlife protection laws".to_string(),
            regulation: "Wildlife Protection Law; CITES Convention; Entry-Exit Plant Quarantine Law".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "71".to_string(),
            name: "Precious Metals and Stones (Restricted)".to_string(),
            reason: "Gold, silver, platinum and precious stones are restricted from cross-border e-commerce import; special approval required".to_string(),
            regulation: "Precious Metal Import Management Regulations; PBOC Gold Management Regulations".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "7108".to_string(),
            name: "Gold and Gold Products".to_string(),
            reason: "Non-monetary gold is restricted from cross-border e-commerce import; PBOC approval required for gold import".to_string(),
            regulation: "PBOC Gold Import Management Regulations; Precious Metal Management Regulations".to_string(),
            severity: "Critical".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "24".to_string(),
            name: "Tobacco Products".to_string(),
            reason: "Tobacco and tobacco products are restricted from cross-border e-commerce import; special license required".to_string(),
            regulation: "Tobacco Monopoly Law; Cross-border E-commerce Retail Import Positive List".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "2208".to_string(),
            name: "Distilled Spirits (Over 60% ABV)".to_string(),
            reason: "High-proof spirits exceeding 60% ABV are classified as hazardous and prohibited from cross-border e-commerce import".to_string(),
            regulation: "Dangerous Goods Transport Regulations; Cross-border E-commerce Negative List".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "8710".to_string(),
            name: "Tanks and Armored Fighting Vehicles".to_string(),
            reason: "Military vehicles and armored fighting vehicles are strictly prohibited from import".to_string(),
            regulation: "Military Equipment Import-Export Control Law; Customs Prohibited Items List".to_string(),
            severity: "Critical".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "8901".to_string(),
            name: "Cruise Ships and Cargo Vessels".to_string(),
            reason: "Large vessels are outside the scope of cross-border e-commerce retail import".to_string(),
            regulation: "Cross-border E-commerce Retail Import Positive List Scope Limitations".to_string(),
            severity: "Medium".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "88".to_string(),
            name: "Aircraft and Spacecraft (Restricted)".to_string(),
            reason: "Aircraft and spacecraft are outside the scope of cross-border e-commerce retail import; special approval required".to_string(),
            regulation: "Civil Aviation Law; Military Equipment Import-Export Control Law".to_string(),
            severity: "High".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "8600".to_string(),
            name: "Railway Rolling Stock (Restricted)".to_string(),
            reason: "Railway locomotives and rolling stock are outside the scope of cross-border e-commerce retail import".to_string(),
            regulation: "Railway Safety Management Regulations; Cross-border E-commerce Scope Limitations".to_string(),
            severity: "Medium".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "9506".to_string(),
            name: "Weapons and Guns (Sporting)".to_string(),
            reason: "Sporting guns, crossbows and similar weapons are prohibited from cross-border e-commerce import".to_string(),
            regulation: "Firearms Control Law; Customs Prohibited Items List".to_string(),
            severity: "Critical".to_string(),
        },
        ProhibitedItem {
            hs_code_prefix: "3822".to_string(),
            name: "Diagnostic or Laboratory Reagents".to_string(),
            reason: "Diagnostic reagents and laboratory chemicals are restricted from cross-border e-commerce import; IVD devices require NMPA registration".to_string(),
            regulation: "Medical Device Supervision Regulations; IVD Reagent Management Measures".to_string(),
            severity: "High".to_string(),
        },
    ]
}

pub fn get_ccc_cert_items() -> Vec<CccCertItem> {
    vec![
        CccCertItem {
            hs_code_prefix: "8415".to_string(),
            product_name: "Air Conditioners".to_string(),
            ccc_category: "Household and Similar Electrical Appliances".to_string(),
            cert_required: true,
            standard: "GB 4706.1, GB 4706.32".to_string(),
            note: "All air conditioners (split, window, portable) require CCC certification before import and sale".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8418".to_string(),
            product_name: "Refrigerators and Freezers".to_string(),
            ccc_category: "Household and Similar Electrical Appliances".to_string(),
            cert_required: true,
            standard: "GB 4706.1, GB 4706.13".to_string(),
            note: "Household refrigerators, freezers and combined refrigerator-freezers require CCC certification".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8450".to_string(),
            product_name: "Washing Machines".to_string(),
            ccc_category: "Household and Similar Electrical Appliances".to_string(),
            cert_required: true,
            standard: "GB 4706.1, GB 4706.24".to_string(),
            note: "Household washing machines and washer-dryers require CCC certification".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8504".to_string(),
            product_name: "Electrical Transformers and Power Supplies".to_string(),
            ccc_category: "Low-Voltage Electrical Apparatus".to_string(),
            cert_required: true,
            standard: "GB 4943.1, GB/T 14714".to_string(),
            note: "Power adapters, chargers and SMPS units require CCC certification; commonly triggered in cross-border e-commerce for electronics accessories".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8516".to_string(),
            product_name: "Electric Water Heaters and Hair Care Appliances".to_string(),
            ccc_category: "Household and Similar Electrical Appliances".to_string(),
            cert_required: true,
            standard: "GB 4706.1, GB 4706.11, GB 4706.15".to_string(),
            note: "Electric water heaters, hair dryers, curling irons and similar heating appliances require CCC certification".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8517".to_string(),
            product_name: "Mobile Phones and Communication Equipment".to_string(),
            ccc_category: "Telecom Terminal Equipment".to_string(),
            cert_required: true,
            standard: "GB 4943.1, YD/T 1592".to_string(),
            note: "Smartphones, feature phones and mobile communication terminals require CCC certification and network access license (NAL)".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8528".to_string(),
            product_name: "Television Receivers and Monitors".to_string(),
            ccc_category: "Audio and Video Equipment".to_string(),
            cert_required: true,
            standard: "GB 4943.1, GB 13837, GB 17625.1".to_string(),
            note: "TV sets, monitors and display devices require CCC certification; applicable to cross-border e-commerce electronics".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8471".to_string(),
            product_name: "Computers and Data Processing Equipment".to_string(),
            ccc_category: "Information Technology Equipment".to_string(),
            cert_required: true,
            standard: "GB 4943.1, GB/T 9813.1".to_string(),
            note: "Desktop computers, laptops, tablets and servers require CCC certification; very common in cross-border e-commerce".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8525".to_string(),
            product_name: "Cameras and Video Recording Equipment".to_string(),
            ccc_category: "Information Technology Equipment".to_string(),
            cert_required: true,
            standard: "GB 4943.1, GB 13837".to_string(),
            note: "Digital cameras, webcams and video recording equipment require CCC certification".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8531".to_string(),
            product_name: "Electrical Sound and Visual Signalling Equipment".to_string(),
            ccc_category: "Low-Voltage Electrical Apparatus".to_string(),
            cert_required: true,
            standard: "GB 14048.1, GB 14048.5".to_string(),
            note: "Indicator panels, alarm systems and signalling devices require CCC certification".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8536".to_string(),
            product_name: "Electrical Plugs, Sockets and Switches".to_string(),
            ccc_category: "Low-Voltage Electrical Apparatus".to_string(),
            cert_required: true,
            standard: "GB 2099.1, GB 16915.1, GB 1002".to_string(),
            note: "Plugs, socket-outlets, switches and connectors require CCC certification; high risk item in cross-border e-commerce".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8537".to_string(),
            product_name: "Electrical Control and Distribution Panels".to_string(),
            ccc_category: "Low-Voltage Electrical Apparatus".to_string(),
            cert_required: true,
            standard: "GB 7251.1, GB 14048.1".to_string(),
            note: "Control panels and distribution boards require CCC certification".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8540".to_string(),
            product_name: "Cathode Ray Tubes and Display Panels".to_string(),
            ccc_category: "Information Technology Equipment".to_string(),
            cert_required: true,
            standard: "GB 4943.1, GB 8898".to_string(),
            note: "Display panels and CRT tubes require CCC certification when incorporated into end-use products".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8544".to_string(),
            product_name: "Insulated Wire and Cable".to_string(),
            ccc_category: "Wire and Cable Products".to_string(),
            cert_required: true,
            standard: "GB/T 5023, GB/T 12706, GB 31247".to_string(),
            note: "Insulated wires and cables rated up to 450/750V require CCC certification; common component in electronics import".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8501".to_string(),
            product_name: "Electric Motors".to_string(),
            ccc_category: "Small Power Motors".to_string(),
            cert_required: true,
            standard: "GB 12350, GB/T 5171".to_string(),
            note: "Small and medium power electric motors require CCC certification".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8703".to_string(),
            product_name: "Passenger Motor Vehicles".to_string(),
            ccc_category: "Motor Vehicle Products".to_string(),
            cert_required: true,
            standard: "GB 7258, GB 11551, GB 18352".to_string(),
            note: "Passenger vehicles require CCC certification; strict emission and safety standards apply; parallel import requires CCC certification as well".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8708".to_string(),
            product_name: "Automotive Parts and Components".to_string(),
            ccc_category: "Motor Vehicle Parts".to_string(),
            cert_required: true,
            standard: "GB 8410, GB 11566, GB 17354".to_string(),
            note: "Key automotive components (brakes, lamps, mirrors, glass) require CCC certification; important for auto parts cross-border e-commerce".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "9405".to_string(),
            product_name: "Lamps and Lighting Fittings".to_string(),
            ccc_category: "Lighting Equipment".to_string(),
            cert_required: true,
            standard: "GB 7000.1, GB 17625.1, GB 17743".to_string(),
            note: "LED lamps, fixed luminaires and lighting fittings require CCC certification; very common in cross-border e-commerce".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "6403".to_string(),
            product_name: "Footwear with Outer Soles of Rubber or Plastics".to_string(),
            ccc_category: "Footwear Products".to_string(),
            cert_required: false,
            standard: "GB 25038, QB/T 2675".to_string(),
            note: "Footwear does not require mandatory CCC certification, but quality inspection per GB standards is recommended for cross-border e-commerce compliance".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "9022".to_string(),
            product_name: "Medical X-ray and Radiation Equipment".to_string(),
            ccc_category: "Medical Devices".to_string(),
            cert_required: true,
            standard: "GB 9706.1, GB 9706.3, GB 9706.11".to_string(),
            note: "Medical radiation equipment requires both CCC certification and NMPA medical device registration".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8414".to_string(),
            product_name: "Air Pumps, Compressors and Ventilating Fans".to_string(),
            ccc_category: "Household and Similar Electrical Appliances".to_string(),
            cert_required: true,
            standard: "GB 4706.1, GB 4343.1".to_string(),
            note: "Household ventilating fans and air treatment appliances require CCC certification".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "8507".to_string(),
            product_name: "Electric Accumulators (Li-ion Batteries)".to_string(),
            ccc_category: "Battery Products".to_string(),
            cert_required: true,
            standard: "GB 31241, GB/T 31484, GB 38031".to_string(),
            note: "Lithium-ion batteries and battery packs require CCC certification; critical compliance item for cross-border e-commerce electronics".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "6110".to_string(),
            product_name: "Knitted Garments (Sweaters, Pullovers)".to_string(),
            ccc_category: "Textile Products".to_string(),
            cert_required: false,
            standard: "GB 18401, GB/T 29862".to_string(),
            note: "Textile products do not require CCC certification but must comply with GB 18401 (formaldehyde, pH, azo dyes) for safety; important for cross-border e-commerce apparel".to_string(),
        },
        CccCertItem {
            hs_code_prefix: "6203".to_string(),
            product_name: "Men's or Boys' Suits and Outer Garments".to_string(),
            ccc_category: "Textile Products".to_string(),
            cert_required: false,
            standard: "GB 18401, GB/T 29862, GB 31701".to_string(),
            note: "Textile products do not require CCC certification but must comply with GB 18401 safety standards; children's clothing has additional GB 31701 requirements".to_string(),
        },
    ]
}
